### ISSUE TITLE
fill_kma.dist() code

### ISSUE THREAD

**Issue by ellyyuyang** [hmmartiny/mcr_metagenomes#1]
Hello developers, 

Thanks for the tool!

I am wondering about where I can find the definition of the function **fill_kma.dist()**? 
https://github.com/hmmartiny/mcr_metagenomes/blob/601a0a54b02acd0cb4cd674abb05c5a48ce615de/notebooks/mcr_plots.Rmd#L451

Thanks!
Yu

**Comment by hmmartiny** [comment]
Hi Yu, 

You can find the function `fill_kma.dist` here: https://github.com/hmmartiny/mcr_metagenomes/blob/601a0a54b02acd0cb4cd674abb05c5a48ce615de/src/extra_funcs.R#L36

Best
Hannah-Marie

**Comment by ellyyuyang** [comment]
> Owner

Thanks Hannah-Marie, for your super fast response!

Best,
Yu
